name: CI

on:
  push:
    branches:
      - master
      - '*.x'
    tags:
      - '*'
  pull_request:
  schedule:
    # Weekly Monday 7AM build
    - cron: "0 7 * * 1"

jobs:
  ci:
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install stsci.image
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      - name: Run tests
        run: |
          pytest
